services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    networks:
      - frontend
    environment:
      TZ: ${TZ}
      GF_SERVER_ROOT_URL: "https://${GF_SERVER_ROOT_URL}"
      GF_AUTH_GENERIC_OAUTH_ENABLED: "True"
      GF_AUTH_GENERIC_OAUTH_NAME: "authentik"
      GF_AUTH_GENERIC_OAUTH_CLIENT_ID: "${GF_AUTH_GENERIC_OAUTH_CLIENT_ID}"
      GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: "${GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET}"
      GF_AUTH_GENERIC_OAUTH_SCOPES: "openid profile email"
      GF_AUTH_GENERIC_OAUTH_AUTH_URL: "${GF_AUTH_GENERIC_OAUTH_AUTH_URL}"
      GF_AUTH_GENERIC_OAUTH_TOKEN_URL: "${GF_AUTH_GENERIC_OAUTH_TOKEN_URL}"
      GF_AUTH_GENERIC_OAUTH_API_URL: "${GF_AUTH_GENERIC_OAUTH_API_URL}"
      GF_AUTH_SIGNOUT_REDIRECT_URL: "${GF_AUTH_SIGNOUT_REDIRECT_URL}"
      GF_AUTH_OAUTH_AUTO_LOGIN: "True"
      GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH: "contains(groups, 'Grafana Admins') && 'Admin' || contains(groups, 'Grafana Editors') && 'Editor' || 'Viewer'"
    labels:
      - traefik.enable=true
      - traefik.http.routers.grafana.rule=Host(`${GF_SERVER_ROOT_URL}`)
      - traefik.http.routers.grafana.entrypoints=websecure
      - traefik.http.routers.grafana.tls=true
      - traefik.http.services.grafana-service.loadbalancer.server.port=3000
      - com.centurylinklabs.watchtower.enable=true
    volumes:
      - "${MOUNT_ROOT}/grafana:/var/lib/grafana:rw"

networks:
  frontend:
    external: true